### ISSUE TITLE
usage with angular2

### ISSUE THREAD

**Issue by gate3** [joshbalfour/node-cognitive-services#12]
Hi, Can anybody help me with using this library with angular2. I am interested in emotion detection.

**Comment by mslourens** [comment]
this is a Node.js module, so you need a Node.js API to be able to use this module in Angular2. I use it in Ionic and implemented Handwriting recognition with this module in my API. If you don't have a Node.js API, you can always use POST and GET requests directly. More info about how to use the API directly with Angular (or Javascript in general) can be found [here](https://docs.microsoft.com/en-us/azure/cognitive-services/emotion/quickstarts/javascript)
