### ISSUE TITLE
cognitiveServices.computerVision is not a constructor

### ISSUE THREAD

**Issue by rogeryu23** [joshbalfour/node-cognitive-services#2]
Hi when I follow the samples on the page but I got the error for the following
const computerVision = new cognitiveServices.computerVision({
    API_KEY: yourApiKey
})

**Comment by kirkins** [comment]
I'm trying this and haave the same issue

**Comment by julietsvq** [comment]
try 
cognitiveServices.computerVision({ 
API_KEY: yourApiKey
 }) 
instead

**Comment by julietsvq** [comment]
Try
const computerVision = cognitiveServices.computerVision({ 
API_KEY: yourApiKey
 })
instead

**Comment by NodeUrsa** [comment]
It's working but after pass that it shows this error.

**Comment by NodeUrsa** [comment]
Got response undefined
Unhandled rejection StatusCodeError: 404 - {"statusCode":404,"message":"Resource not found"}
    at new StatusCodeError (/home/dev/workspace/vision/node_modules/cognitive-services/node_modules/request-promise/lib/errors.js:32:15)
    at Request.RP$callback [as _callback] (/home/dev/workspace/vision/node_modules/cognitive-services/node_modules/request-promise/lib/rp.js:77:29)
    at Request.self.callback (/home/dev/workspace/vision/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/dev/workspace/vision/node_modules/request/request.js:1081:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/home/dev/workspace/vision/node_modules/request/request.js:1001:12)
    at IncomingMessage.g (events.js:291:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by xurei** [comment]
I have the same issue. Did anyone find a solution to this ?

**Comment by mikemaccana** [comment]
@xurei yes @julietsvq did.

Would love to hear from @joshbalfour as to whether docs are wrong (which mention to use `new`) or whether this should actually be a constructor.

**Comment by OR13** [comment]
certainly appears the docs are incorrect and computerVision should be initialized like so:

```
      var computerVision = cognitiveServices.computerVision({
            API_KEY: 'YOUR_KEY'
        })
```

**Comment by jaylandro** [comment]
I had trouble getting all of the node computer vision examples to work as well. Here is what I cam up with for reading a file from the file system and analyzing it.

`const fetch = require('node-fetch')
const fs = require('fs')

let params = {
    "maxCandidates": "1",
};

let image = fs.readFileSync('./image.jpg')

fetch('https://api.projectoxford.ai/vision/v1.0/analyze?visualFeatures=Description&language=en', {
		method: 'POST',
		body: image,
		headers: {
			'Content-Type': 'application/octet-stream', 
			'Ocp-Apim-Subscription-Key': 'API_KEY'
		}
	})
    .then(res => {
        return res.json();
    }).then(body => {
        console.log(body.description);
    })`

**Comment by rupalipemare** [comment]
HI , even I get the same error Unhandled rejection StatusCodeError: 404 - {"statusCode":404,"message":"Resource not found"}

**Comment by egandalf** [comment]
@jaylandro Thanks for sharing your manual solution. Here's the mod to have it work with an image url: 

`fetch('https://api.projectoxford.ai/vision/v1.0/analyze?visualFeatures=Description&language=en', {
    method: 'POST',
    body: JSON.stringify({ "url" : testImageUrl }),
    headers: {
        'Content-Type': 'application/json',
        'Ocp-Apim-Subscription-Key' : msCogKey1
    }
}).then(res => {...`

**Comment by nwhitmont** [comment]
docs updated in PR #11

**Comment by nwhitmont** [comment]
FYI - Project Oxford API URLs have been depreciated @joshbalfour 

>Starting on 1/17, our endpoints will be changing. If your API is currently using "api.projectoxford.ai" endpoint, you will need to switch to the new API endpoint starting on 1/17. If you continue to use the legacy endpoint after 1/17, you may experience latency. To know if you are affected, visit your API homepage and click on the “API Reference” button for more information on your API’s endpoint change. We thank you for your cooperation as we continue to improve our services. The old API endpoints will be deprecated 90 days following this change (on 4/15).

**Comment by joshbalfour** [comment]
@nwhitmont thanks for the heads up, is there a new root we an bulk find/replace or is it not going to be that easy?

**Comment by nwhitmont** [comment]
@joshbalfour there are multiple datacenters that support Cognitive services now, for example: https://westus.dev.cognitive.microsoft.com/docs/services/56f91f2d778daf23d8ec6739/operations/56f91f2e778daf14a499e1fa

For Computer Vision:
- West US - westus.api.cognitive.microsoft.com
- East US 2 - eastus2.api.cognitive.microsoft.com
- West Central US - westcentralus.api.cognitive.microsoft.com
- West Europe - westeurope.api.cognitive.microsoft.com
- Southeast Asia - southeastasia.api.cognitive.microsoft.com

**Comment by Alioveyu** [comment]
I use `face.detect` function and got
> Unhandled rejection StatusCodeError: 404 - {"statusCode":404,"message":"Resource not found"}

**Comment by miparnisari** [comment]
This is fixed in https://github.com/joshbalfour/node-cognitive-services/pull/13
