### ISSUE TITLE
Official node sdk cognitive services packages with samples

### ISSUE THREAD

**Issue by amarzavery** [joshbalfour/node-cognitive-services#40]
Hello folks,

I stumbled across this repo. The work done in this repo is really cool 👍 ! 

I would like to take this opportunity to let everyone know that we(Azure SDK Team) have published a bunch of node.js sdks with TypeScript type definitions, API calls that support callback as well as promise and good runnable samples for cognitive services. We have published individual packages for each service in cognitive service and have also published rollup packages containing individual packages in 4 of the 5 categories.

### 3 rollup packages
- https://www.npmjs.com/package/azure-cognitiveservices-language (contains ->(textanalytics|spellcheck))
- https://www.npmjs.com/package/azure-cognitiveservices-search (contains ->
 (entity|news|image|web|custom|video))
- https://www.npmjs.com/package/azure-cognitiveservices-vision (contains -> (computervision|face|contentmoderator))

## Management plane for creating the cognitive services account and getting the keys for a specific service
- https://www.npmjs.com/package/azure-arm-cognitiveservices

## Samples
- https://github.com/Azure-Samples/cognitive-services-node-sdk-samples

Any feedback is highly appreciated 👍 .

@miparnisari, @joshbalfour, @dfberry 

/cc @ronak25

**Comment by miparnisari** [comment]
That's cool, i'll try to have a look at the packages when I have some time.
