### ISSUE TITLE
Endpoint is not supported

### ISSUE THREAD

**Issue by HybridFox** [joshbalfour/node-cognitive-services#45]
## Expected Behavior
Return results

## Actual Behavior
Endpoint https://westcentralus.api.cognitive.microsoft.com/vision/v1.0 is not supported.

## Relevant Code

```javascript
const compVis = new cognitiveServices.computerVision({
    apiKey: 'xxx',
    endpoint: 'https://westcentralus.api.cognitive.microsoft.com/vision/v1.0'
});
```

## Specifications

  - Node version: v7.8.0
  - Package version: 0.6.2

**Comment by miparnisari** [comment]
Please change
```
    endpoint: 'https://westcentralus.api.cognitive.microsoft.com/vision/v1.0'
```
to
```
    endpoint: 'https://westcentralus.api.cognitive.microsoft.com'
```

**Comment by HybridFox** [comment]
Thank you!

**Comment by Amirbahal** [comment]
same issue here , I have made any possible change 

const apiKey = "xxx";
const endpoint = "https://face**mybrand.cognitiveservices.azure.com";

const face = new cognitiveServices.face({
    apiKey,
    endpoint
});
