### ISSUE TITLE
404 not found error

### ISSUE THREAD

**Issue by ZhengkunWang** [joshbalfour/node-cognitive-services#5]
I have tried to call the api with the lib, but I got 404 error, I'm sure my img url is available, I'm not sure where is the 404 error raised? Return from mircosoft or lib.
I use the link to test below code:
https://runkit.com/npm/cognitive-services#face---identify
<pre>
const cognitiveServices = require("cognitive-services");
const face = cognitiveServices.face({
    API_KEY: 'replaced with my api key'
});
 
const parameters = {
    returnFaceId: "true",
    returnFaceLandmarks: "false"
};
const body = {
    "url": "http://www.yoka.com/dna/pics/ba1da9b9/2/d3d1a7dbe59d13a1331.jpg"
};
 
 
face.detect({
        parameters,
        body
    })
    .then((response) => {
        console.log('Got response', response);
        return response;
    })
    .catch((err) => {
        console.error('Encountered error making request:', err);
    });
</pre>

**Comment by ZhengkunWang** [comment]
TypeError: Cannot read property 'body' of undefined
    at face.detect.then (/Users/zkwang/newbie/newbie/src/server/api.js:77:19)
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by brucedjones** [comment]
Same issue with the emotion API, I had a look through the sources and it looks like on line 15 in api.js, the uri isn't being formed correctly. In my case it is making a request to https://api.projectoxford.ai/undefined

**Comment by miparnisari** [comment]
This is fixed in https://github.com/joshbalfour/node-cognitive-services/pull/13
