### ISSUE TITLE
speakerRegonition.js body not defined error

### ISSUE THREAD

**Issue by epcalus** [joshbalfour/node-cognitive-services#6]
I am getting this error when trying to use the speakerRecognition class

./node_modules/cognitive-services/api/speakerRecognition.js:508
                body,
ReferenceError: body is not defined

When looking at the source in speakerRecognition.js I see that body is not passed into the function

self.listAllSupportedVerificationPhrases = ({
        parameters
    }) => {

....
...
Line 508 is object "body" passed in the makeRequest in the verify Parameters call below
return verifyParameters(operation, parameters)
            .then(makeRequest({
                operation,
                parameters,
                body,
                API_KEY
            }));

**Comment by miparnisari** [comment]
@epcalus this is fixed in PR https://github.com/joshbalfour/node-cognitive-services/pull/13
