### ISSUE TITLE
Bing Speech is not working

### ISSUE THREAD

**Issue by laukinfungdavid** [joshbalfour/node-cognitive-services#60]
When I use the Bing Speech Service, it always returns service unavailable. I discover that the path for the Bing Speech is wrong. 
Now the path is "speech/{recognitionMode}/cognitiveservices/v1".
But the correct path should be "speech/recognition/{recognitionMode}/cognitiveservices/v1"

**Comment by miparnisari** [comment]
Merged your PR. Thanks for the contribution!
