### ISSUE TITLE
Dependency error: 'Error: Cannot find module 'promise-retry'

### ISSUE THREAD

**Issue by dsrodenas** [joshbalfour/node-cognitive-services#67]
Hello,
I'm updating my program to use the 1.2.1 version and it is not working for me. The error message is: **'Error: Cannot find module 'promise-retry'**. I have the same issue with ```sleep-promise``` dependency. Both are defined in the package.json as devDependencies. If I move the dependencies ```sleep-promise``` and ```promise-retry```  to dependencies section everything works fine.

Am I doing something wrong or it is a real issue and both dependencies should be moved to dependencies?

**Comment by miparnisari** [comment]
You're right. They should be dependencies. Thanks for reporting this! Can you please try again?

**Comment by dsrodenas** [comment]
@miparnisari  I've tried with 1.2.2 and works fine. Thanks a lot!!
