### ISSUE TITLE
createAPersonGroup returns error: Cannot read property 'hasOwnProperty' of null

### ISSUE THREAD

**Issue by Amirbahal** [joshbalfour/node-cognitive-services#74]
## Expected Behavior

Returning an ok 200 and creating a person group to which I can add persons. 

## Actual Behavior

Returning the error: Cannot read property 'hasOwnProperty' of null

## Relevant Code

face.createAPersonGroup({
    parameters: {
        "personGroupId": "asdfasdfadsfadfdasf",
        "name" : "Test Person Group",
        "userData": "this-is-test-data"
    },
    Body: {
    }
}).then(res => {
    console.log(res);
}).catch(err => {
    console.log("Create A PERSON Group: " + err);
});

## Specifications

  - Node version: 12.9.1
  - Package version: 1.2.3

**Comment by miparnisari** [comment]
Sorry for the late response. Can you please try this?

```js
face.createAPersonGroup({
  parameters: {
  "personGroupId": "asdfasdfadsfadfdasf",
  },
  body: {
    "name" : "Test Person Group",
    "userData": "this-is-test-data"
  }
}).then(res => {
  console.log(res);
}).catch(err => {
  console.log("Create A PERSON Group: " + err);
});
```

**Comment by Amirbahal** [comment]
Thank you for replying @miparnisari 
I will give try this one. :)
