### ISSUE TITLE
filterQueryParams not taken into account in bingVideoSearchV7

### ISSUE THREAD

**Issue by i4nch1k** [joshbalfour/node-cognitive-services#80]
## Expected Behavior
The following code
```javascript
new bingVideoSearchV7({apiKey: "MY_KEY"})
      .search({
        parameters: {
          q: "some search",
          freshness: "Day",
        },
      });
```
should fetch relevant video results ["discovered within the last 24 hours"](https://docs.microsoft.com/en-us/rest/api/cognitiveservices-bingsearch/bing-video-api-v7-reference#filter-query-parameters) because of the freshness parameter value.

## Actual Behavior
The request fails with the message "Parameter "freshness" could not be found in the list of supported parameters",
although the parameter is in the [list of valid parameters](https://github.com/joshbalfour/node-cognitive-services/blob/4a54789fc16d127bf2153a5b9e566b7bbe49f7f7/src/search/bingVideoSearchV7.js#L181).

## Relevant Code
The bug seems to come from 
```javascript
var operation = {
      "path": "bing/v7.0/videos/search",
      "method": "GET",
      "headers": this.headers,
      "parameters": this.parameters.filter(function (p) {
             return p.name == 'cc' || p.name == 'count' || p.name == 'id' || p.name == 'mkt' || p.name == 'offset' || p.name == 'q' || p.name == 'safeSearch' || p.name == 'setLang' || p.name == 'textDecorations' || p.name == 'textFormat';
      }).concat(this.queryStringParams)
};
```
where [queryStringParams is concatenated](https://github.com/joshbalfour/node-cognitive-services/blob/4a54789fc16d127bf2153a5b9e566b7bbe49f7f7/src/search/bingVideoSearchV7.js#L223) instead of filterQueryParams [like in bingImageSearchV7](https://github.com/joshbalfour/node-cognitive-services/blob/4a54789fc16d127bf2153a5b9e566b7bbe49f7f7/src/search/bingImageSearchV7.js#L390) where the filter parameters work well.

## Possible solution
```javascript
var operation = {
      "path": "bing/v7.0/videos/search",
      "method": "GET",
      "headers": this.headers,
      "parameters": this.parameters.filter(function (p) {
             return p.name == 'cc' || p.name == 'count' || p.name == 'id' || p.name == 'mkt' || p.name == 'offset' || p.name == 'q' || p.name == 'safeSearch' || p.name == 'setLang' || p.name == 'textDecorations' || p.name == 'textFormat';
      }).concat(this.filterQueryParams)
};
```

## Specifications

  - Node version: 12.20.0
  - Package version: 1.2.4

**Comment by miparnisari** [comment]
Thanks @i4nch1k ! Fixed in 1.2.6.
