### ISSUE TITLE
For Face Api : Unhandled rejection StatusCodeError: 404 - {"statusCode":404,"message":"Resource not found"}

### ISSUE THREAD

**Issue by rupalipemare** [joshbalfour/node-cognitive-services#9]
const cognitiveServices = require('cognitive-services');
const face = cognitiveServices.face({
    API_KEY: "Replaced with my api "
})
const parameters = {
    returnFaceId: "true",
    returnFaceLandmarks: "true",
    returnFaceAttributes: "age,gender,headPose,smile,facialHair,glasses"
};
const body = {
    "url" : "http://techstory.in/wp-content/uploads/2015/02/sachin-tendulkar-sifr-651867782.jpg"
};
face.detect({
        parameters,
        body
    })
    .then((response) => {
            return console.log('Got response', response);
    })
    .catch((err) => {
        return console.error('Encountered error making request:', err);
    });
I used code getting the unhandled rejection error .
Also checked the host that is used in cognitive-servcies/api/face.js Changed tried changing to one that is used in microsoft api reference in open console testing , but then getting other error like Unhandled rejection RequestError: Error: getaddrinfo ENOTFOUND https https:443.

Would like to know the answer from you Sir .

**Comment by mjmgooch** [comment]
@rupalipemare I edited api.js line 7 in the following way, this may help:

`
let path = operation.path;
`

It was set to 'operation.uriTemplate' which doesn't exist in the operation array.

**Comment by miparnisari** [comment]
This is fixed in https://github.com/joshbalfour/node-cognitive-services/pull/13
